<?php
declare(strict_types=1);
function assert_deploy(bool $ok, string $message): void {
    if (!$ok) throw new RuntimeException($message);
}
$root = dirname(__DIR__);
$nginx = file_get_contents($root.'/deploy/nginx-hache-miner-https.conf.example');
$pool = file_get_contents($root.'/deploy/php-fpm-hache-miner.conf.example');
$timer = file_get_contents($root.'/deploy/systemd/hache-miner-poll.timer');
$service = file_get_contents($root.'/deploy/systemd/hache-miner-poll.service');
$health = file_get_contents($root.'/public/health.php');
$activate = file_get_contents($root.'/deploy/activate.sh');
$installer = file_get_contents($root.'/deploy/install-https-web.sh');
$collector = file_get_contents($root.'/deploy/enable-collector-timer.sh');
$importer = file_get_contents($root.'/bin/import-shared-salad-key.php');
$rotator = file_get_contents($root.'/bin/rotate-master-key.php');
$rotateWrap = file_get_contents($root.'/deploy/rotate-master-key.sh');
$poolOverview = file_get_contents($root.'/app/pool-overview.php');
$dashboard = file_get_contents($root.'/public/index.php');
$upgrade = file_get_contents($root.'/deploy/upgrade-miner-vhost.sh');
$dashboard = file_get_contents($root.'/public/index.php');
$css = file_get_contents($root.'/public/style.css');
$diagnostics = file_get_contents($root.'/app/diagnostics.php');
$poll = file_get_contents($root.'/bin/poll.php');
$reallocate = file_get_contents($root.'/app/reallocate.php');
$interactiveAuto = file_get_contents($root.'/app/interactive-auto.php');
$interactiveRunner = file_get_contents($root.'/bin/interactive-auto.php');
$interactiveService = file_get_contents($root.'/deploy/systemd/hache-miner-interactive-auto.service');
$interactiveTimer = file_get_contents($root.'/deploy/systemd/hache-miner-interactive-auto.timer');
$interactiveInstall = file_get_contents($root.'/deploy/enable-interactive-auto.sh');
$monitor = file_get_contents($root.'/app/monitor.php');
$finance = file_get_contents($root.'/app/finances.php');
$credits = file_get_contents($root.'/app/salad-credits.php');
$creditsSql = file_get_contents($root.'/database/005_salad_credit_snapshots.sql');
$creditsMigration = file_get_contents($root.'/deploy/apply-credit-snapshots-migration.sh');
$creditsImport = file_get_contents($root.'/bin/import-credit-snapshots.php');
$receiptsImporter = file_get_contents($root.'/bin/import-salad-receipts.php');
$receiptsWrapper = file_get_contents($root.'/deploy/import-salad-receipts.sh');
$accounting = file_get_contents($root.'/app/accounting.php');
$accountingSql = file_get_contents($root.'/database/004_accounting_events.sql');
assert_deploy(str_contains($nginx, 'root /srv/hache-miner/current/public'), 'Webroot must be public');
assert_deploy(str_contains($nginx, 'location ~ \\.php$ { return 404; }'), 'Other PHP scripts must not be served');
assert_deploy(str_contains($nginx, 'ssl_certificate_key'), 'TLS required');
assert_deploy(str_contains($pool, 'pm.max_children = 1'), 'FPM memory cap required');
assert_deploy(str_contains($pool, 'auto_prepend_file'), 'Private runtime loader required');
assert_deploy(str_contains($timer, 'OnCalendar=*:2/5'), 'Five-minute schedule required');
assert_deploy(str_contains($service, 'MemoryMax=128M'), 'Poller memory cap required');
assert_deploy(str_contains($service, 'NoNewPrivileges=yes'), 'Poller privilege lockdown required');
assert_deploy(str_contains($health, 'http_response_code(503)'), 'Readiness failure must be unavailable');
assert_deploy(!is_file($root.'/.env'), 'No environment file in repository');
assert_deploy(str_contains($activate, 'chmod -R a+rX'), 'Release permissions must allow service user to read public code');
assert_deploy(str_contains($activate, "-name 'runtime.php'"), 'Private runtime files must not be published');
assert_deploy(str_contains($installer, 'certbot certonly --non-interactive --agree-tos --webroot'), 'New certificate must use non-disruptive webroot flow');
assert_deploy(str_contains($installer, 'trap rollback EXIT'), 'Installer requires rollback on error');
assert_deploy(str_contains($installer, 'installed_site=1'), 'Installer must distinguish own vhost changes');
assert_deploy(str_contains($installer, 'php-fpm8.4 -t'), 'PHP pool configuration must pass validation before reload');
assert_deploy(str_contains($installer, 'nginx -t'), 'Nginx configuration must pass validation before reload');
assert_deploy(str_contains($installer, 'available_kib >= 131072'), 'Installer must protect existing host under memory pressure');
assert_deploy(str_contains($installer, 'sleep 1'), 'Installer must wait for async PHP-FPM reload');
assert_deploy(str_contains($installer, 'pool_ready=0'), 'Installer must track the dedicated pool socket readiness');
assert_deploy(str_contains($installer, 'after 30-second wait'), 'Installer must timeout and rollback stalled PHP-FPM pools');
assert_deploy(str_contains($installer, "acme_ready=0"), 'ACME location must be checked after async Nginx reload');
assert_deploy(str_contains($installer, "MINER_ACME_ROUTE_READY"), 'ACME route must return the exact challenge probe');
assert_deploy(str_contains($installer, "https_ready=0"), 'HTTPS readiness must handle asynchronous reload');
assert_deploy(str_contains($installer, "--noproxy '*'"), 'Local preflight must bypass outbound proxies');
assert_deploy(str_contains($nginx, 'SCRIPT_FILENAME $realpath_root/index.php'), 'FPM entrypoint must follow immutable releases, not cached symlink');
assert_deploy(str_contains($nginx, 'SCRIPT_FILENAME $realpath_root/health.php'), 'Health entrypoint must follow immutable release');
assert_deploy(str_contains($upgrade, 'MINER_VHOST_ROLLED_BACK'), 'Dedicated vhost rollback required');
assert_deploy(str_contains($upgrade, 'Recordar este dispositivo durante 30 días'), 'Nginx rollout requires new PHP UI verification');
assert_deploy(str_contains($collector, 'hache-salad-monitor.timer'), 'Collector must preserve the existing Salad monitor');
assert_deploy(str_contains($collector, 'miner_shared_salad_api_key()'), 'Collector requires shared Salad key before activation');
assert_deploy(str_contains($collector, 'MINER_COLLECTOR_ROLLED_BACK'), 'Collector must roll back failed activation');
assert_deploy(str_contains($collector, 'result >= 1'), 'Collector must verify API connectivity before scheduling');
assert_deploy(str_contains($importer, 'posix_geteuid() !== 0'), 'Salad import must require root');
assert_deploy(str_contains($importer, "'/etc/hache-salad-monitor.env'"), 'Source must be the existing private legacy env file');
assert_deploy(str_contains($importer, "miner_put_secret('salad:api-key'"), 'Importer must store the shared key encrypted');
assert_deploy(str_contains($importer, 'SALAD_SHARED_KEY_ALREADY_CONFIGURED'), 'Importer must not rotate an existing shared key');
assert_deploy(str_contains($rotator, 'SELECT id,ciphertext,nonce FROM secret_store ORDER BY id FOR UPDATE'), 'Rotation locks existing encrypted records');
assert_deploy(str_contains($rotator, 'miner_seal($plain,$newKey)'), 'Rotation must re-encrypt every record');
assert_deploy(str_contains($rotator, 'if ($db instanceof PDO && $db->inTransaction()) $db->rollBack();'), 'Rotation must rollback SQL on failure');
assert_deploy(str_contains($rotateWrap, 'mariadb-dump --single-transaction'), 'Rotation must create private SQL backup');
assert_deploy(str_contains($rotateWrap, 'systemctl stop "$timer"'), 'Rotation must pause only miner timer');
assert_deploy(str_contains($dashboard, 'mobile-stack') && str_contains($dashboard, 'data-label="Grupo"'), 'Mobile group cards must include readable captions');
assert_deploy(str_contains($css, '@media(max-width:720px)') && str_contains($css, 'attr(data-label)'), 'Mobile view must not squeeze desktop table columns');
assert_deploy(str_contains($diagnostics, 'miner_recent_group_statuses()'), 'Only recent distinct instances may be counted as ready');
assert_deploy(str_contains($diagnostics, "state']==='running'"), 'Ready count must require running state');
assert_deploy(str_contains($poll, '$failed>0?'), 'Partial instance/log failures must not be reported as successful full collection');
assert_deploy(str_contains($poolOverview, "SELECT id,organization,label,address FROM wallets"), 'Overview must load registered PRL wallet identities');
assert_deploy(str_contains($poolOverview, '$byAddress[$addr]'), 'Wallet balances must be deduplicated by address');
assert_deploy(str_contains($poolOverview, "'all_balances_fresh'"), 'Incomplete recent coverage must not be shown as complete');
assert_deploy(str_contains($dashboard, "miner_pool_overview()"), 'Dashboard must display actual pool observations');
assert_deploy(!str_contains($poolOverview,'miner_get_secret('), 'Wallet overview must not read private API keys');
assert_deploy(str_contains($dashboard, "page==='monitor'") && str_contains($dashboard,'page=monitor'), 'Authenticated dynamic monitor must be navigable');
assert_deploy(str_contains($dashboard, "page==='finance'") && str_contains($dashboard,'page=finance'), 'Finance view must be separate from operational state');
assert_deploy(str_contains($monitor, 'WHERE last_seen_at >= UTC_TIMESTAMP()-INTERVAL 8 HOUR ORDER BY organization,project_name,group_name'), 'Monitor cannot be limited to fixed group names');
assert_deploy(str_contains($monitor, 'GROUP BY group_id,instance_id'), 'Instances must be deduplicated by ID');
assert_deploy(str_contains($monitor, "INTERVAL 15 MINUTE"), 'Live-state must be bounded by freshness');
assert_deploy(!str_contains($monitor,'miner_get_secret('), 'Read-only monitor must not query credentials');
assert_deploy(!str_contains($monitor, '/reallocate'), 'Legacy reallocation must not duplicate in miner monitor');
assert_deploy(str_contains($finance, 'reconciled_charges') && str_contains($finance, 'estimated_cost_usd'), 'Verified charges and estimated costs must remain distinct');
assert_deploy(str_contains($dashboard, "page==='reallocate'") && str_contains($dashboard, 'miner_reallocation_password('), 'Manual action must have separate authenticated validation');
assert_deploy(str_contains($dashboard,'miner_check_csrf();'), 'CSRF must be checked for all write operations');
assert_deploy(str_contains($dashboard, 'unset($_SESSION[\'reallocation_challenge\']);'), 'Challenge must be single use before Salad POST');
assert_deploy(str_contains($reallocate, 'miner_reallocation_target($groupId,$instanceId)'), 'Server must validate live tracked target');
assert_deploy(str_contains($reallocate, 'miner_reallocation_live_matches($live,$instanceId)'), 'Server must verify exact live instance with Salad');
assert_deploy(str_contains($reallocate, "manual_reallocate_intent"), 'Audit intent must precede non-idempotent request');
assert_deploy(str_contains($reallocate, "GET_LOCK(?,2)"), 'Manual requests must be serialized');
assert_deploy(str_contains($reallocate, "INTERVAL 15 MINUTE"), 'Manual reallocation must have cooldown');
assert_deploy(!str_contains($poll,'miner_reallocation_execute('), 'Poller must never reallocate an instance');
assert_deploy(str_contains($reallocate, 'function miner_reallocation_cooldown_index('), 'Monitor cooldown must be read in one DB pass');
assert_deploy(str_contains($reallocate, 'function miner_reallocation_cooldown_seconds('), 'Manual confirmation must enforce current cooldown');
assert_deploy(!str_contains($reallocate, 'hashrate_ths') && !str_contains($reallocate, 'break_even_ths'), 'Manual override must not depend on hash or profit thresholds');
assert_deploy(str_contains($dashboard, "manual_reallocate_success") && str_contains($dashboard, "unset(\$_SESSION['manual_reallocate_success'])"), 'Success must come from a single-use authenticated server-side flash');
assert_deploy(!str_contains($dashboard, "isset(\$_GET['reallocated'])"), 'User-controlled GET must never forge success');
assert_deploy(str_contains($dashboard, "miner_reallocation_cooldown_seconds("), 'Confirmation screen must check cooldown');
assert_deploy(str_contains($dashboard, "ceil(\$cooldown/60)"), 'Monitor must label the manual cooldown per instance');
assert_deploy(str_contains($dashboard, "hash_file('sha256',__DIR__.'/style.css')"), 'CSS href must change when deployed contents change; Cloudflare caches styles for hours');
assert_deploy(str_contains($dashboard, 'class="monitor-entry monitor-entry--'), 'Every group must remain a visible card');
assert_deploy(str_contains($dashboard, 'class="monitor-node-action"'), 'Manual action must be visibly attached to each instance, not hidden in details');
assert_deploy(strpos($dashboard, 'class="monitor-node-action"') < strpos($dashboard, '<details class="monitor-group">'), 'Manual action must not be hidden inside collapsed technical details');
assert_deploy(str_contains($dashboard, 'miner_reallocation_fingerprint($g,'), 'Cooldown remains scoped to exact instance');
assert_deploy(str_contains($css, '.monitor-entry{') && str_contains($css, '.monitor-node--red') && str_contains($css, '.monitor-node--yellow') && str_contains($css, '.monitor-node--green'), 'Card and traffic-light styles must exist');
assert_deploy(str_contains($dashboard, 'class="monitor-trend"') && str_contains($dashboard,'<polyline points='), 'Each observed GPU must support a genuine trend line');
assert_deploy(str_contains($poll, 'miner_monitor_instance_log_metrics($logs,$nodes)'), 'Collector must attribute metrics to known instance IDs');
assert_deploy(str_contains($poll, "hashrate_ths,gpu_model,watts"), 'Per-instance observations must store actual metrics');
assert_deploy(str_contains($monitor, 'miner_monitor_log_instance('), 'Multi-replica GPU log IDs must be verified, not guessed');
assert_deploy(str_contains($monitor, 'INTERVAL 8 HOUR'), 'Old deleted groups must be hidden but not deleted');
assert_deploy(!str_contains($monitor, 'DELETE FROM group_state'), 'Filter-only retention must preserve financial and diagnostic history');
assert_deploy(str_contains($accountingSql, 'UNIQUE KEY uq_accounting_ref'), 'Receipt references need DB uniqueness');
assert_deploy(str_contains($accounting, 'miner_accounting_ready()'), 'Accounting requires an explicit DB migration');
assert_deploy(str_contains($dashboard, 'name="movement_reference"'), 'Ledger events must be tied to receipts');
assert_deploy(str_contains($accounting, "prl_transfer"), 'PRL transfer cannot become cash income');
assert_deploy(str_contains($receiptsImporter,'posix_geteuid()!==0'), 'Receipt importer must run only as root');
assert_deploy(str_contains($receiptsImporter,'hash_file(\'sha256\''), 'Importer must verify private evidence checksum');
assert_deploy(str_contains($receiptsImporter,'miner_accounting_validate('), 'Importer must run the same validations as admin UI');
assert_deploy(str_contains($receiptsImporter,'Receipt conflict; abort import'), 'Duplicate receipt mismatch must abort');
assert_deploy(str_contains($receiptsImporter,'$db->beginTransaction()'), 'Receipt ingestion must be transactionally atomic');
assert_deploy(str_contains($receiptsWrapper,'mariadb-dump --single-transaction'), 'Import must back up DB before writing receipts');
assert_deploy(str_contains($receiptsWrapper,'PRIVATE_SOURCE_OR_RUNTIME_NOT_FOUND'), 'Import must require private staged file');
assert_deploy(!str_contains($receiptsImporter,'miner_reallocation_execute('), 'Import cannot touch GPU lifecycle');
assert_deploy(str_contains($creditsSql, 'UNIQUE KEY uq_credit_evidence'), 'Each screenshot evidence must be deduplicated');
assert_deploy(str_contains($credits, "miner_credit_snapshots_ready()"), 'Financial overview must work before migration');
assert_deploy(str_contains($credits, "cents['issued_usd']"), 'Issued must reconcile to consumed, available and expired');
assert_deploy(str_contains($dashboard, "miner_credit_snapshot_overview()"), 'Official billing must be visible only under admin finance');
assert_deploy(str_contains($dashboard, 'action===\'credit_snapshot\''), 'Recording credits requires the authenticated write route');
assert_deploy(str_contains($creditsMigration, 'mariadb-dump --single-transaction'), 'Credit migration needs root-only backup');
assert_deploy(str_contains($creditsImport, "posix_geteuid()!==0"), 'Private screenshot importer must require root');
assert_deploy(str_contains($creditsImport, "hash_file('sha256'"), 'Screenshot import must be pinned to private evidence checksum');
assert_deploy(!str_contains($creditsImport, 'miner_reallocation_execute('), 'Financial importer must not modify GPUs');
assert_deploy(str_contains($interactiveAuto, "g.organization='interactive'"), 'Interactive watchdog must not modify HACHE groups');
assert_deploy(str_contains($interactiveAuto, "summary LIKE '%[pearlhash]%'"), 'Only verified PRL algorithm may trigger automated reallocation');
assert_deploy(str_contains($interactiveAuto, "INTERVAL 60 MINUTE"), 'Automated requests must wait after manual intervention');
assert_deploy(str_contains($interactiveAuto, "'auto_reallocate_intent'"), 'Durable intent required before API POST');
assert_deploy(str_contains($interactiveAuto, "miner_reallocation_live_matches("), 'Live Salad instance identity must be verified');
assert_deploy(str_contains($interactiveAuto, "miner_auto_low_prl_metric("), 'Policy must require sustained confirmed per-instance observations');
assert_deploy(str_contains($interactiveAuto, "GET_LOCK(?,2)"), 'Manual and auto share one per-instance MySQL lock');
assert_deploy(str_contains($reallocate, "'auto_reallocate_intent'"), 'Manual handler must honor recent automatic relocation');
assert_deploy(str_contains($interactiveRunner, 'if(!miner_auto_enabled())'), 'Runner must default to no POST in dry-run');
assert_deploy(str_contains($interactiveService, 'User=hache-miner') && str_contains($interactiveService,'NoNewPrivileges=yes'), 'New worker must be non-root and sandboxed');
assert_deploy(str_contains($interactiveTimer, 'OnCalendar=*:4/5'), 'Run automation independently every five minutes');
assert_deploy(str_contains($interactiveInstall, 'MINER_INTERACTIVE_AUTO_ENABLED=0'), 'Root installer must run a dry-run before activation');
assert_deploy(str_contains($interactiveInstall, 'LEGACY_HACHE_TIMER_PRESERVED'), 'Installer must preserve existing automatic protection');
assert_deploy(!str_contains($poll, 'miner_auto_execute('), 'Read-only collector must stay read-only');
assert_deploy(str_contains($monitor, "function miner_monitor_live_hashrate("), 'Dashboard must calculate an evidence-backed per-instance aggregate');
assert_deploy(str_contains($monitor, "'live_hashrate'=>miner_monitor_live_hashrate("), 'Live total must be derived from the same observations as cards');
assert_deploy(str_contains($dashboard, 'class="monitor-live-summary"'), 'Hashrate total must be immediately visible on monitor');
assert_deploy(str_contains($dashboard, "'measured'") && str_contains($dashboard, "'missing'"), 'Coverage counts must be visible alongside the sum');
assert_deploy(str_contains($dashboard, "Última medición efectiva por GPU") || str_contains($dashboard,'última medición efectiva por GPU'), 'Aggregate must say it is based on effective readings');
assert_deploy(str_contains($css, '.monitor-live-value'), 'Prominent numeric summary styling must be present');
assert_deploy(!str_contains($poll, 'miner_auto_execute('), 'Collector must remain read-only');
assert_deploy(str_contains($monitor,'function miner_monitor_log_metric(') && str_contains($monitor, "'watts'=>"), 'Universal monitor requires model-agnostic metric extraction and optional wattage');
assert_deploy(str_contains($monitor,"'containerGroupInstanceId'"), 'Salad instance identity aliases must be recognized');
assert_deploy(str_contains($monitor,"'group_log_observation'"), 'Unattributed logs must be retained only as group evidence');
assert_deploy(str_contains($dashboard,'class="monitor-group-evidence"'), 'UI must show a separate unattributed group log reading');
assert_deploy(str_contains($dashboard,'No se reparten entre las instancias ni se suman al total general.'), 'Unknown instance identity must never inflate confirmed TH/s');
assert_deploy(str_contains($css,'.monitor-group-evidence{'), 'Group-only evidence needs a distinct style');
assert_deploy(!str_contains($poll,'miner_reallocation_execute('), 'Read-only collector cannot relocate GPUs');
echo "PASS deploy-isolation-regression\n";
