<?php
declare(strict_types=1);
function assert_deploy(bool $ok, string $message): void {
    if (!$ok) throw new RuntimeException($message);
}
$root = dirname(__DIR__);
$nginx = file_get_contents($root.'/deploy/nginx-hache-miner-https.conf.example');
$pool = file_get_contents($root.'/deploy/php-fpm-hache-miner.conf.example');
$timer = file_get_contents($root.'/deploy/systemd/hache-miner-poll.timer');
$service = file_get_contents($root.'/deploy/systemd/hache-miner-poll.service');
$health = file_get_contents($root.'/public/health.php');
$activate = file_get_contents($root.'/deploy/activate.sh');
$installer = file_get_contents($root.'/deploy/install-https-web.sh');
$collector = file_get_contents($root.'/deploy/enable-collector-timer.sh');
$importer = file_get_contents($root.'/bin/import-shared-salad-key.php');
$rotator = file_get_contents($root.'/bin/rotate-master-key.php');
$rotateWrap = file_get_contents($root.'/deploy/rotate-master-key.sh');
$poolOverview = file_get_contents($root.'/app/pool-overview.php');
$dashboard = file_get_contents($root.'/public/index.php');
$upgrade = file_get_contents($root.'/deploy/upgrade-miner-vhost.sh');
$dashboard = file_get_contents($root.'/public/index.php');
$css = file_get_contents($root.'/public/style.css');
$diagnostics = file_get_contents($root.'/app/diagnostics.php');
$poll = file_get_contents($root.'/bin/poll.php');
$reallocate = file_get_contents($root.'/app/reallocate.php');
$monitor = file_get_contents($root.'/app/monitor.php');
$finance = file_get_contents($root.'/app/finances.php');
assert_deploy(str_contains($nginx, 'root /srv/hache-miner/current/public'), 'Webroot must be public');
assert_deploy(str_contains($nginx, 'location ~ \\.php$ { return 404; }'), 'Other PHP scripts must not be served');
assert_deploy(str_contains($nginx, 'ssl_certificate_key'), 'TLS required');
assert_deploy(str_contains($pool, 'pm.max_children = 1'), 'FPM memory cap required');
assert_deploy(str_contains($pool, 'auto_prepend_file'), 'Private runtime loader required');
assert_deploy(str_contains($timer, 'OnCalendar=*:2/5'), 'Five-minute schedule required');
assert_deploy(str_contains($service, 'MemoryMax=128M'), 'Poller memory cap required');
assert_deploy(str_contains($service, 'NoNewPrivileges=yes'), 'Poller privilege lockdown required');
assert_deploy(str_contains($health, 'http_response_code(503)'), 'Readiness failure must be unavailable');
assert_deploy(!is_file($root.'/.env'), 'No environment file in repository');
assert_deploy(str_contains($activate, 'chmod -R a+rX'), 'Release permissions must allow service user to read public code');
assert_deploy(str_contains($activate, "-name 'runtime.php'"), 'Private runtime files must not be published');
assert_deploy(str_contains($installer, 'certbot certonly --non-interactive --agree-tos --webroot'), 'New certificate must use non-disruptive webroot flow');
assert_deploy(str_contains($installer, 'trap rollback EXIT'), 'Installer requires rollback on error');
assert_deploy(str_contains($installer, 'installed_site=1'), 'Installer must distinguish own vhost changes');
assert_deploy(str_contains($installer, 'php-fpm8.4 -t'), 'PHP pool configuration must pass validation before reload');
assert_deploy(str_contains($installer, 'nginx -t'), 'Nginx configuration must pass validation before reload');
assert_deploy(str_contains($installer, 'available_kib >= 131072'), 'Installer must protect existing host under memory pressure');
assert_deploy(str_contains($installer, 'sleep 1'), 'Installer must wait for async PHP-FPM reload');
assert_deploy(str_contains($installer, 'pool_ready=0'), 'Installer must track the dedicated pool socket readiness');
assert_deploy(str_contains($installer, 'after 30-second wait'), 'Installer must timeout and rollback stalled PHP-FPM pools');
assert_deploy(str_contains($installer, "acme_ready=0"), 'ACME location must be checked after async Nginx reload');
assert_deploy(str_contains($installer, "MINER_ACME_ROUTE_READY"), 'ACME route must return the exact challenge probe');
assert_deploy(str_contains($installer, "https_ready=0"), 'HTTPS readiness must handle asynchronous reload');
assert_deploy(str_contains($installer, "--noproxy '*'"), 'Local preflight must bypass outbound proxies');
assert_deploy(str_contains($nginx, 'SCRIPT_FILENAME $realpath_root/index.php'), 'FPM entrypoint must follow immutable releases, not cached symlink');
assert_deploy(str_contains($nginx, 'SCRIPT_FILENAME $realpath_root/health.php'), 'Health entrypoint must follow immutable release');
assert_deploy(str_contains($upgrade, 'MINER_VHOST_ROLLED_BACK'), 'Dedicated vhost rollback required');
assert_deploy(str_contains($upgrade, 'Recordar este dispositivo durante 30 días'), 'Nginx rollout requires new PHP UI verification');
assert_deploy(str_contains($collector, 'hache-salad-monitor.timer'), 'Collector must preserve the existing Salad monitor');
assert_deploy(str_contains($collector, 'miner_shared_salad_api_key()'), 'Collector requires shared Salad key before activation');
assert_deploy(str_contains($collector, 'MINER_COLLECTOR_ROLLED_BACK'), 'Collector must roll back failed activation');
assert_deploy(str_contains($collector, 'result >= 1'), 'Collector must verify API connectivity before scheduling');
assert_deploy(str_contains($importer, 'posix_geteuid() !== 0'), 'Salad import must require root');
assert_deploy(str_contains($importer, "'/etc/hache-salad-monitor.env'"), 'Source must be the existing private legacy env file');
assert_deploy(str_contains($importer, "miner_put_secret('salad:api-key'"), 'Importer must store the shared key encrypted');
assert_deploy(str_contains($importer, 'SALAD_SHARED_KEY_ALREADY_CONFIGURED'), 'Importer must not rotate an existing shared key');
assert_deploy(str_contains($rotator, 'SELECT id,ciphertext,nonce FROM secret_store ORDER BY id FOR UPDATE'), 'Rotation locks existing encrypted records');
assert_deploy(str_contains($rotator, 'miner_seal($plain,$newKey)'), 'Rotation must re-encrypt every record');
assert_deploy(str_contains($rotator, 'if ($db instanceof PDO && $db->inTransaction()) $db->rollBack();'), 'Rotation must rollback SQL on failure');
assert_deploy(str_contains($rotateWrap, 'mariadb-dump --single-transaction'), 'Rotation must create private SQL backup');
assert_deploy(str_contains($rotateWrap, 'systemctl stop "$timer"'), 'Rotation must pause only miner timer');
assert_deploy(str_contains($dashboard, 'mobile-stack') && str_contains($dashboard, 'data-label="Grupo"'), 'Mobile group cards must include readable captions');
assert_deploy(str_contains($css, '@media(max-width:720px)') && str_contains($css, 'attr(data-label)'), 'Mobile view must not squeeze desktop table columns');
assert_deploy(str_contains($diagnostics, 'miner_recent_group_statuses()'), 'Only recent distinct instances may be counted as ready');
assert_deploy(str_contains($diagnostics, "state']==='running'"), 'Ready count must require running state');
assert_deploy(str_contains($poll, '$failed>0?'), 'Partial instance/log failures must not be reported as successful full collection');
assert_deploy(str_contains($poolOverview, "SELECT id,organization,label,address FROM wallets"), 'Overview must load registered PRL wallet identities');
assert_deploy(str_contains($poolOverview, '$byAddress[$addr]'), 'Wallet balances must be deduplicated by address');
assert_deploy(str_contains($poolOverview, "'all_balances_fresh'"), 'Incomplete recent coverage must not be shown as complete');
assert_deploy(str_contains($dashboard, "miner_pool_overview()"), 'Dashboard must display actual pool observations');
assert_deploy(!str_contains($poolOverview,'miner_get_secret('), 'Wallet overview must not read private API keys');
assert_deploy(str_contains($dashboard, "page==='monitor'") && str_contains($dashboard,'page=monitor'), 'Authenticated dynamic monitor must be navigable');
assert_deploy(str_contains($dashboard, "page==='finance'") && str_contains($dashboard,'page=finance'), 'Finance view must be separate from operational state');
assert_deploy(str_contains($monitor, 'FROM group_state ORDER BY organization,project_name,group_name'), 'Monitor cannot be limited to fixed group names');
assert_deploy(str_contains($monitor, 'GROUP BY group_id,instance_id'), 'Instances must be deduplicated by ID');
assert_deploy(str_contains($monitor, "INTERVAL 15 MINUTE"), 'Live-state must be bounded by freshness');
assert_deploy(!str_contains($monitor,'miner_get_secret('), 'Read-only monitor must not query credentials');
assert_deploy(!str_contains($monitor, '/reallocate'), 'Legacy reallocation must not duplicate in miner monitor');
assert_deploy(str_contains($finance, 'reconciled_charges') && str_contains($finance, 'estimated_cost_usd'), 'Verified charges and estimated costs must remain distinct');
assert_deploy(str_contains($dashboard, "page==='reallocate'") && str_contains($dashboard, 'miner_reallocation_password('), 'Manual action must have separate authenticated validation');
assert_deploy(str_contains($dashboard,'miner_check_csrf();'), 'CSRF must be checked for all write operations');
assert_deploy(str_contains($dashboard, 'unset($_SESSION[\'reallocation_challenge\']);'), 'Challenge must be single use before Salad POST');
assert_deploy(str_contains($reallocate, 'miner_reallocation_target($groupId,$instanceId)'), 'Server must validate live tracked target');
assert_deploy(str_contains($reallocate, 'miner_reallocation_live_matches($live,$instanceId)'), 'Server must verify exact live instance with Salad');
assert_deploy(str_contains($reallocate, "manual_reallocate_intent"), 'Audit intent must precede non-idempotent request');
assert_deploy(str_contains($reallocate, "GET_LOCK(?,2)"), 'Manual requests must be serialized');
assert_deploy(str_contains($reallocate, "INTERVAL 15 MINUTE"), 'Manual reallocation must have cooldown');
assert_deploy(!str_contains($poll,'miner_reallocation_execute('), 'Poller must never reallocate an instance');
echo "PASS deploy-isolation-regression\n";
