<?php
declare(strict_types=1);
function assert_deploy(bool $ok, string $message): void {
    if (!$ok) throw new RuntimeException($message);
}
$root = dirname(__DIR__);
$nginx = file_get_contents($root.'/deploy/nginx-hache-miner-https.conf.example');
$pool = file_get_contents($root.'/deploy/php-fpm-hache-miner.conf.example');
$timer = file_get_contents($root.'/deploy/systemd/hache-miner-poll.timer');
$service = file_get_contents($root.'/deploy/systemd/hache-miner-poll.service');
$health = file_get_contents($root.'/public/health.php');
$activate = file_get_contents($root.'/deploy/activate.sh');
$installer = file_get_contents($root.'/deploy/install-https-web.sh');
$collector = file_get_contents($root.'/deploy/enable-collector-timer.sh');
$importer = file_get_contents($root.'/bin/import-shared-salad-key.php');
$rotator = file_get_contents($root.'/bin/rotate-master-key.php');
$rotateWrap = file_get_contents($root.'/deploy/rotate-master-key.sh');
$upgrade = file_get_contents($root.'/deploy/upgrade-miner-vhost.sh');
assert_deploy(str_contains($nginx, 'root /srv/hache-miner/current/public'), 'Webroot must be public');
assert_deploy(str_contains($nginx, 'location ~ \\.php$ { return 404; }'), 'Other PHP scripts must not be served');
assert_deploy(str_contains($nginx, 'ssl_certificate_key'), 'TLS required');
assert_deploy(str_contains($pool, 'pm.max_children = 1'), 'FPM memory cap required');
assert_deploy(str_contains($pool, 'auto_prepend_file'), 'Private runtime loader required');
assert_deploy(str_contains($timer, 'OnCalendar=*:2/5'), 'Five-minute schedule required');
assert_deploy(str_contains($service, 'MemoryMax=128M'), 'Poller memory cap required');
assert_deploy(str_contains($service, 'NoNewPrivileges=yes'), 'Poller privilege lockdown required');
assert_deploy(str_contains($health, 'http_response_code(503)'), 'Readiness failure must be unavailable');
assert_deploy(!is_file($root.'/.env'), 'No environment file in repository');
assert_deploy(str_contains($activate, 'chmod -R a+rX'), 'Release permissions must allow service user to read public code');
assert_deploy(str_contains($activate, "-name 'runtime.php'"), 'Private runtime files must not be published');
assert_deploy(str_contains($installer, 'certbot certonly --non-interactive --agree-tos --webroot'), 'New certificate must use non-disruptive webroot flow');
assert_deploy(str_contains($installer, 'trap rollback EXIT'), 'Installer requires rollback on error');
assert_deploy(str_contains($installer, 'installed_site=1'), 'Installer must distinguish own vhost changes');
assert_deploy(str_contains($installer, 'php-fpm8.4 -t'), 'PHP pool configuration must pass validation before reload');
assert_deploy(str_contains($installer, 'nginx -t'), 'Nginx configuration must pass validation before reload');
assert_deploy(str_contains($installer, 'available_kib >= 131072'), 'Installer must protect existing host under memory pressure');
assert_deploy(str_contains($installer, 'sleep 1'), 'Installer must wait for async PHP-FPM reload');
assert_deploy(str_contains($installer, 'pool_ready=0'), 'Installer must track the dedicated pool socket readiness');
assert_deploy(str_contains($installer, 'after 30-second wait'), 'Installer must timeout and rollback stalled PHP-FPM pools');
assert_deploy(str_contains($installer, "acme_ready=0"), 'ACME location must be checked after async Nginx reload');
assert_deploy(str_contains($installer, "MINER_ACME_ROUTE_READY"), 'ACME route must return the exact challenge probe');
assert_deploy(str_contains($installer, "https_ready=0"), 'HTTPS readiness must handle asynchronous reload');
assert_deploy(str_contains($installer, "--noproxy '*'"), 'Local preflight must bypass outbound proxies');
assert_deploy(str_contains($nginx, 'SCRIPT_FILENAME $realpath_root/index.php'), 'FPM entrypoint must follow immutable releases, not cached symlink');
assert_deploy(str_contains($nginx, 'SCRIPT_FILENAME $realpath_root/health.php'), 'Health entrypoint must follow immutable release');
assert_deploy(str_contains($upgrade, 'MINER_VHOST_ROLLED_BACK'), 'Dedicated vhost rollback required');
assert_deploy(str_contains($upgrade, 'Recordar este dispositivo durante 30 días'), 'Nginx rollout requires new PHP UI verification');
assert_deploy(str_contains($collector, 'hache-salad-monitor.timer'), 'Collector must preserve the existing Salad monitor');
assert_deploy(str_contains($collector, 'miner_shared_salad_api_key()'), 'Collector requires shared Salad key before activation');
assert_deploy(str_contains($collector, 'MINER_COLLECTOR_ROLLED_BACK'), 'Collector must roll back failed activation');
assert_deploy(str_contains($collector, 'result >= 1'), 'Collector must verify API connectivity before scheduling');
assert_deploy(str_contains($importer, 'posix_geteuid() !== 0'), 'Salad import must require root');
assert_deploy(str_contains($importer, "'/etc/hache-salad-monitor.env'"), 'Source must be the existing private legacy env file');
assert_deploy(str_contains($importer, "miner_put_secret('salad:api-key'"), 'Importer must store the shared key encrypted');
assert_deploy(str_contains($importer, 'SALAD_SHARED_KEY_ALREADY_CONFIGURED'), 'Importer must not rotate an existing shared key');
assert_deploy(str_contains($rotator, 'SELECT id,ciphertext,nonce FROM secret_store ORDER BY id FOR UPDATE'), 'Rotation locks existing encrypted records');
assert_deploy(str_contains($rotator, 'miner_seal($plain,$newKey)'), 'Rotation must re-encrypt every record');
assert_deploy(str_contains($rotator, 'if ($db instanceof PDO && $db->inTransaction()) $db->rollBack();'), 'Rotation must rollback SQL on failure');
assert_deploy(str_contains($rotateWrap, 'mariadb-dump --single-transaction'), 'Rotation must create private SQL backup');
assert_deploy(str_contains($rotateWrap, 'systemctl stop "$timer"'), 'Rotation must pause only miner timer');
echo "PASS deploy-isolation-regression\n";
